apiVersion: apps/v1
kind: Deployment
metadata:
  name: picalc
  labels:
    app: picalc
spec:
  selector:
    matchLabels:
      app: picalc
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
  template:
    metadata:
      labels:
        app: picalc
    spec:
      containers:
      - name: picalc
        image: __IMAGE__@__DIGEST__
        ports:
        - name: http-server
          containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: ibm-cr-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: picalc
  labels:
    app: picalc
spec:
  ports:
  - port: 8080
    targetPort: http-server
  selector:
    app: picalc
  type: NodePort
